# Generated by Django 5.0.4 on 2024-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='test2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test9',
            field=models.BooleanField(default=False),
        ),
    ]
