# Generated by Django 5.0.4 on 2024-04-23 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta_sa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pregunta', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('imagen', models.CharField(blank=True, max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('instruccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('instruccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='opcion_sa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inciso', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=200)),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.pregunta_sa')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta_sa',
            name='seccion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.seccion'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.test'),
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('Tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.tipo_usuario')),
            ],
        ),
    ]
