# Generated by Django 5.0.4 on 2024-06-04 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='opcion_ipp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inciso', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='opcion_sa',
            name='valor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta1', models.TextField(blank=True)),
                ('pregunta2', models.TextField(blank=True)),
                ('pregunta3', models.TextField(blank=True)),
                ('pregunta4', models.TextField(blank=True)),
                ('pregunta5', models.TextField(blank=True)),
                ('pregunta6', models.TextField(blank=True)),
                ('pregunta7', models.TextField(blank=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='pregunta_hspq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pregunta', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=500)),
                ('seccion', models.CharField(max_length=200)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='opcion_hspq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inciso', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.pregunta_hspq')),
            ],
        ),
        migrations.CreateModel(
            name='pregunta_ipp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pregunta', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=500)),
                ('seccion', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='respuesta1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_test', models.IntegerField()),
                ('id_apartado', models.IntegerField()),
                ('id_pregunta', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('opcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.opcion_sa')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_test', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('seccion', models.IntegerField()),
                ('opcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.opcion_ipp')),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.pregunta_ipp')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_test', models.IntegerField()),
                ('id_pregunta', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('seccion', models.CharField(max_length=200)),
                ('opcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.opcion_hspq')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
